name: Run CI Pipeline
on:
  push:
permissions: {}

jobs:
  Trigger_Pipeline:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI Pipeline
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: ci.yml
          repo: 15-WG-Tron/pipelines-and-templates
          ref: main
          token: ${{ secrets.ORG_TOKEN }}
          inputs: '{"repository_name" : "${{ github.repository }}" ,  "base_ref" : "main", "head_ref" : "${{ github.sha }}"}'
